name       : amdvlk
version    : 2020.2.2
release    : 1
source     :
    - https://github.com/GPUOpen-Drivers/AMDVLK/releases/download/v-2020.Q2.2/amdvlk_2020.Q2.2_amd64.deb : c1966f16b20abf229b741a662ccb2569361896f704b7078f35b378f5bdf7fef9
license    :
    - MIT
component  : xorg.display
extract    : no
strip      : no
summary    : AMD's standalone Vulkan driver.
description: |
    AMD's standalone Vulkan driver.
builddeps  :
    - binutils
    - tar
setup      : |
    # Extract deb
    ar -xv $sources/*.deb
    tar -xf data.tar.xz 
install    : |
    install -m755 -d $installdir/%libdir%
    install -m755 -d $installdir/usr/share/vulkan/icd.d
    install -m755 -d $installdir/usr/share/licenses/amdvlk

    install usr/lib/x86_64-linux-gnu/amdvlk64.so $installdir/%libdir%
    install usr/lib/x86_64-linux-gnu/spvgen.so $installdir/%libdir%
    install $pkgfiles/json/Redhat/amd_icd64.json $installdir/usr/share/vulkan/icd.d/
    install $pkgfiles/LICENSE.txt $installdir/usr/share/licenses/amdvlk/
    
    # sed -i "s#/lib64#/lib#g" $installdir/usr/share/vulkan/icd.d/amd_icd64.json
